[global]
# act_on_success=false
inputdirectory = "/tmp/testdataset"
hierarchical=true
traversal="topdown"
parallel=true
regex=true
scp_configuration = "ssh.json"
owncloud_configuration = "owncloud.json"
common_actions = {do_on_invalid=[["all", "show_warning", ["log_to_file", "errors.txt"]]]}
common_conditions = {is_3d_channel=[["all", "is_tif_file", "is_3d_img", "filename_ends_with_integer"]], dir_only=[["all", "isdir", ["not", "is_hidden"]]]}
file_lists=[{name="in", aggregator=[["filepath","sort","unique","shared_list_to_file"]]},
              {name="out", aggregator=[[["change_path", "/tmp/output"],"filepath","sort","unique","shared_list_to_file"]]},
              {name="objects", aggregator=[["describe_objects","concat_to_table"]]},
              {name="channels", aggregator=[["describe_image","concat_to_table"]]},]
[any]
conditions=["never"]
actions=["do_on_invalid"]

[level_1]
conditions=["dir_only"]
actions=["do_on_invalid"]

[level_2]
all=true
conditions=["dir_only", "ends_with_integer", ["startswith", "Replicate"]]
actions=["do_on_invalid"]

[level_3]
conditions=["dir_only"]
actions=["do_on_invalid"]

[level_4]
all=true
conditions=["dir_only", ["startswith", "Serie"], "ends_with_integer"]
actions=["do_on_invalid"]

[level_5]
conditions=["is_3d_channel"]
actions=["do_on_invalid"]
counter_actions=[["->", ["in","out","objects","channels"]]]
